### ISSUE TITLE
12/10 README.mdの語句をレビューしてほしい

### ISSUE THREAD

**Issue by hirohaku21** [OmeSatoFoundation/Github_Practice#1]
### ファイルに対して改善を指摘する練習をします。
README.mdを書いてみました。

https://github.com/OmeSatoFoundation/Github_Practice/blob/9d4cac238ac913f6af7b8a6e9e0049d50fdc10e9/README.md?plain=1#L10-L17
正しい文章であるか確認していただけますか？
また、おかしい語句がありましたら、正しい語句に置き換えて教えてください。

**Comment by hirohaku21** [comment]
きました。

**Comment by 9bss2203** [comment]
きました。

**Comment by norinorinonori** [comment]
来ました

**Comment by yuito-ochi** [comment]
来ました。

**Comment by KanonMatsu** [comment]
きました。

**Comment by KanonMatsu** [comment]
1. 物置の隅で、ほこりまみれになっている古い人形を見つけた。 
 2. その選手は、十年に一人の逸材だと言われている。 
 3. 私は、この土地で定職に就き、生活の基盤を築いた。 
 4. 議論は難航すると思ったが、すぐに意見がまとまりしっかりと結論が出た。

**Comment by norinorinonori** [comment]
1. 物置の隅で、ほこりまみれになっている古い人形を見つけた。 
 2. その選手は、十年に一人の逸材だと言われている。 
 3. 私は、この土地で定職に就き、生活の基盤を築いた。 
 4. 議論は難航すると思ったが、すぐに意見がまとまりあっさりと結論が出た。

**Comment by yuito-ochi** [comment]
5.市長の責任ある行動が住民の不安を解消し、行政に対する期待が高まった。
6.たっぷり煮込んだ野菜は味が染みて柔らかく、とてもおいしかったです。
7.このテーブルは私が子供のころから使っているので、愛着があり捨てられない。
8.医学だけではなく、法学にも詳しいのが彼の強みだ。

**Comment by 9bss2203** [comment]
市長の責任ある行動が住民の不安を ~~削除~~ **解消** し、行政に対する期待が一気に高まった。 
十分に煮た野菜は味が ~~潤って~~ **染みて** 柔らかく、とてもおいしかった。 
このテーブルは、私が子供の頃から使っているので、 ~~好感~~ **愛着** があって捨てられない。 
医学だけでなく、法学にも詳しいのが彼の ~~重み~~ **強み** だ。 

と思いました。

**Comment by hirohaku21** [comment]
@norinorinonori @KanonMatsu 

4番は何を達成すれば良さそうですか？

**Comment by norinorinonori** [comment]
前半の文章との繋がりで考えるといいのではないでしょうか

**Comment by hirohaku21** [comment]
僕の意見は、相手に日本語が伝われば良いという基準を持っています。

**Comment by hirohaku21** [comment]
このレビューに関する Issue を全てCloseします。
IssueのCloseは、問題が解決、あるいは、会話が長期間ない場合にCloseします。

### ↓ のように書くことで、関連するIssueを全て閉じることができます。
### 書き方はいろいろあります！
close #3, #4, #5
closes #6 
closed #7, #8
fix #9, #10
fixes #11, #12
fixed #13, #14
resolve #15, #16
resolves #17, #18
resolved #19, #20, #21, #22

**Comment by motegi210** [comment]
1. 物置の隅で、ほこりだらけになっている古い人形を見つけた。 
 2. その選手は、十年に一人の天才だと言われている。 
 3. 私は、この土地で定職に就き、生活の基盤を築いた。 
 4. 議論は難航すると思ったが、すぐに意見がまとまりはっきりと結論が出た。

**Comment by motegi210** [comment]
5. 市長の責任ある行動が住民の不安を解消し、行政に対する期待が一気に高まった。 
 6. 十分に煮た野菜は味がしみて柔らかく、とてもおいしかった。 
 7. このテーブルは、私が子供の頃から使っているので、愛着があって捨てられない。 
 8. 医学だけでなく、法学にも詳しいのが彼の強みだ。
